apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: deployment-production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: production
  replicas: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/name: production
    spec:
      containers:
      - image: 257307634175.dkr.ecr.ap-northeast-2.amazonaws.com/project03-ecr:IMAGE_VERSION
        imagePullPolicy: Always
        name: pod-production
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ap-northeast-2-project03-ecr
